// ts2fable 0.7.1
namespace WebGL2.RenderingContext

open Fable.Core

open WebGL.Types

/// The WebGL2RenderingContext interface provides the OpenGL ES 3.0 rendering context for the drawing surface of an HTML <canvas> element.
/// To get an object of this interface, call `getContext()` on a `<canvas>` element, supplying `"webgl2"` as the argument:
/// ```
/// const canvas = document.getElementById('myCanvas');
/// const gl = canvas.getContext('webgl2');
/// ```
[<AllowNullLiteral; CompiledName("WebGL2RenderingContext")>]
type RenderingContext =
    inherit Base
    inherit Overloads
    inherit WebGL.RenderingContext.Base

[<AllowNullLiteral; CompiledName("WebGL2RenderingContextType")>]
type RenderingContextType =
    abstract prototype: RenderingContext with get, set
    [<Emit "new $0($1...)">]
    abstract Create: unit -> obj
    abstract ACTIVE_UNIFORM_BLOCKS: GL.Enum
    abstract ALREADY_SIGNALED: GL.Enum
    abstract ANY_SAMPLES_PASSED: GL.Enum
    abstract ANY_SAMPLES_PASSED_CONSERVATIVE: GL.Enum
    abstract COLOR: GL.Enum
    abstract COLOR_ATTACHMENT1: GL.Enum
    abstract COLOR_ATTACHMENT10: GL.Enum
    abstract COLOR_ATTACHMENT11: GL.Enum
    abstract COLOR_ATTACHMENT12: GL.Enum
    abstract COLOR_ATTACHMENT13: GL.Enum
    abstract COLOR_ATTACHMENT14: GL.Enum
    abstract COLOR_ATTACHMENT15: GL.Enum
    abstract COLOR_ATTACHMENT2: GL.Enum
    abstract COLOR_ATTACHMENT3: GL.Enum
    abstract COLOR_ATTACHMENT4: GL.Enum
    abstract COLOR_ATTACHMENT5: GL.Enum
    abstract COLOR_ATTACHMENT6: GL.Enum
    abstract COLOR_ATTACHMENT7: GL.Enum
    abstract COLOR_ATTACHMENT8: GL.Enum
    abstract COLOR_ATTACHMENT9: GL.Enum
    abstract COMPARE_REF_TO_TEXTURE: GL.Enum
    abstract CONDITION_SATISFIED: GL.Enum
    abstract COPY_READ_BUFFER: GL.Enum
    abstract COPY_READ_BUFFER_BINDING: GL.Enum
    abstract COPY_WRITE_BUFFER: GL.Enum
    abstract COPY_WRITE_BUFFER_BINDING: GL.Enum
    abstract CURRENT_QUERY: GL.Enum
    abstract DEPTH: GL.Enum
    abstract DEPTH24_STENCIL8: GL.Enum
    abstract DEPTH32F_STENCIL8: GL.Enum
    abstract DEPTH_COMPONENT24: GL.Enum
    abstract DEPTH_COMPONENT32F: GL.Enum
    abstract DRAW_BUFFER0: GL.Enum
    abstract DRAW_BUFFER1: GL.Enum
    abstract DRAW_BUFFER10: GL.Enum
    abstract DRAW_BUFFER11: GL.Enum
    abstract DRAW_BUFFER12: GL.Enum
    abstract DRAW_BUFFER13: GL.Enum
    abstract DRAW_BUFFER14: GL.Enum
    abstract DRAW_BUFFER15: GL.Enum
    abstract DRAW_BUFFER2: GL.Enum
    abstract DRAW_BUFFER3: GL.Enum
    abstract DRAW_BUFFER4: GL.Enum
    abstract DRAW_BUFFER5: GL.Enum
    abstract DRAW_BUFFER6: GL.Enum
    abstract DRAW_BUFFER7: GL.Enum
    abstract DRAW_BUFFER8: GL.Enum
    abstract DRAW_BUFFER9: GL.Enum
    abstract DRAW_FRAMEBUFFER: GL.Enum
    abstract DRAW_FRAMEBUFFER_BINDING: GL.Enum
    abstract DYNAMIC_COPY: GL.Enum
    abstract DYNAMIC_READ: GL.Enum
    abstract FLOAT_32_UNSIGNED_INT_24_8_REV: GL.Enum
    abstract FLOAT_MAT2x3: GL.Enum
    abstract FLOAT_MAT2x4: GL.Enum
    abstract FLOAT_MAT3x2: GL.Enum
    abstract FLOAT_MAT3x4: GL.Enum
    abstract FLOAT_MAT4x2: GL.Enum
    abstract FLOAT_MAT4x3: GL.Enum
    abstract FRAGMENT_SHADER_DERIVATIVE_HINT: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_BLUE_SIZE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_RED_SIZE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER: GL.Enum
    abstract FRAMEBUFFER_DEFAULT: GL.Enum
    abstract FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: GL.Enum
    abstract HALF_FLOAT: GL.Enum
    abstract INTERLEAVED_ATTRIBS: GL.Enum
    abstract INT_2_10_10_10_REV: GL.Enum
    abstract INT_SAMPLER_2D: GL.Enum
    abstract INT_SAMPLER_2D_ARRAY: GL.Enum
    abstract INT_SAMPLER_3D: GL.Enum
    abstract INT_SAMPLER_CUBE: GL.Enum
    abstract INVALID_INDEX: GL.Enum
    abstract MAX: GL.Enum
    abstract MAX_3D_TEXTURE_SIZE: GL.Enum
    abstract MAX_ARRAY_TEXTURE_LAYERS: GL.Enum
    abstract MAX_CLIENT_WAIT_TIMEOUT_WEBGL: GL.Enum
    abstract MAX_COLOR_ATTACHMENTS: GL.Enum
    abstract MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: GL.Enum
    abstract MAX_COMBINED_UNIFORM_BLOCKS: GL.Enum
    abstract MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS: GL.Enum
    abstract MAX_DRAW_BUFFERS: GL.Enum
    abstract MAX_ELEMENTS_INDICES: GL.Enum
    abstract MAX_ELEMENTS_VERTICES: GL.Enum
    abstract MAX_ELEMENT_INDEX: GL.Enum
    abstract MAX_FRAGMENT_INPUT_COMPONENTS: GL.Enum
    abstract MAX_FRAGMENT_UNIFORM_BLOCKS: GL.Enum
    abstract MAX_FRAGMENT_UNIFORM_COMPONENTS: GL.Enum
    abstract MAX_PROGRAM_TEXEL_OFFSET: GL.Enum
    abstract MAX_SAMPLES: GL.Enum
    abstract MAX_SERVER_WAIT_TIMEOUT: GL.Enum
    abstract MAX_TEXTURE_LOD_BIAS: GL.Enum
    abstract MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: GL.Enum
    abstract MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS: GL.Enum
    abstract MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS: GL.Enum
    abstract MAX_UNIFORM_BLOCK_SIZE: GL.Enum
    abstract MAX_UNIFORM_BUFFER_BINDINGS: GL.Enum
    abstract MAX_VARYING_COMPONENTS: GL.Enum
    abstract MAX_VERTEX_OUTPUT_COMPONENTS: GL.Enum
    abstract MAX_VERTEX_UNIFORM_BLOCKS: GL.Enum
    abstract MAX_VERTEX_UNIFORM_COMPONENTS: GL.Enum
    abstract MIN: GL.Enum
    abstract MIN_PROGRAM_TEXEL_OFFSET: GL.Enum
    abstract OBJECT_TYPE: GL.Enum
    abstract PACK_ROW_LENGTH: GL.Enum
    abstract PACK_SKIP_PIXELS: GL.Enum
    abstract PACK_SKIP_ROWS: GL.Enum
    abstract PIXEL_PACK_BUFFER: GL.Enum
    abstract PIXEL_PACK_BUFFER_BINDING: GL.Enum
    abstract PIXEL_UNPACK_BUFFER: GL.Enum
    abstract PIXEL_UNPACK_BUFFER_BINDING: GL.Enum
    abstract QUERY_RESULT: GL.Enum
    abstract QUERY_RESULT_AVAILABLE: GL.Enum
    abstract R11F_G11F_B10F: GL.Enum
    abstract R16F: GL.Enum
    abstract R16I: GL.Enum
    abstract R16UI: GL.Enum
    abstract R32F: GL.Enum
    abstract R32I: GL.Enum
    abstract R32UI: GL.Enum
    abstract R8: GL.Enum
    abstract R8I: GL.Enum
    abstract R8UI: GL.Enum
    abstract R8_SNORM: GL.Enum
    abstract RASTERIZER_DISCARD: GL.Enum
    abstract READ_BUFFER: GL.Enum
    abstract READ_FRAMEBUFFER: GL.Enum
    abstract READ_FRAMEBUFFER_BINDING: GL.Enum
    abstract RED: GL.Enum
    abstract RED_INTEGER: GL.Enum
    abstract RENDERBUFFER_SAMPLES: GL.Enum
    abstract RG: GL.Enum
    abstract RG16F: GL.Enum
    abstract RG16I: GL.Enum
    abstract RG16UI: GL.Enum
    abstract RG32F: GL.Enum
    abstract RG32I: GL.Enum
    abstract RG32UI: GL.Enum
    abstract RG8: GL.Enum
    abstract RG8I: GL.Enum
    abstract RG8UI: GL.Enum
    abstract RG8_SNORM: GL.Enum
    abstract RGB10_A2: GL.Enum
    abstract RGB10_A2UI: GL.Enum
    abstract RGB16F: GL.Enum
    abstract RGB16I: GL.Enum
    abstract RGB16UI: GL.Enum
    abstract RGB32F: GL.Enum
    abstract RGB32I: GL.Enum
    abstract RGB32UI: GL.Enum
    abstract RGB8: GL.Enum
    abstract RGB8I: GL.Enum
    abstract RGB8UI: GL.Enum
    abstract RGB8_SNORM: GL.Enum
    abstract RGB9_E5: GL.Enum
    abstract RGBA16F: GL.Enum
    abstract RGBA16I: GL.Enum
    abstract RGBA16UI: GL.Enum
    abstract RGBA32F: GL.Enum
    abstract RGBA32I: GL.Enum
    abstract RGBA32UI: GL.Enum
    abstract RGBA8: GL.Enum
    abstract RGBA8I: GL.Enum
    abstract RGBA8UI: GL.Enum
    abstract RGBA8_SNORM: GL.Enum
    abstract RGBA_INTEGER: GL.Enum
    abstract RGB_INTEGER: GL.Enum
    abstract RG_INTEGER: GL.Enum
    abstract SAMPLER_2D_ARRAY: GL.Enum
    abstract SAMPLER_2D_ARRAY_SHADOW: GL.Enum
    abstract SAMPLER_2D_SHADOW: GL.Enum
    abstract SAMPLER_3D: GL.Enum
    abstract SAMPLER_BINDING: GL.Enum
    abstract SAMPLER_CUBE_SHADOW: GL.Enum
    abstract SEPARATE_ATTRIBS: GL.Enum
    abstract SIGNALED: GL.Enum
    abstract SIGNED_NORMALIZED: GL.Enum
    abstract SRGB: GL.Enum
    abstract SRGB8: GL.Enum
    abstract SRGB8_ALPHA8: GL.Enum
    abstract STATIC_COPY: GL.Enum
    abstract STATIC_READ: GL.Enum
    abstract STENCIL: GL.Enum
    abstract STREAM_COPY: GL.Enum
    abstract STREAM_READ: GL.Enum
    abstract SYNC_CONDITION: GL.Enum
    abstract SYNC_FENCE: GL.Enum
    abstract SYNC_FLAGS: GL.Enum
    abstract SYNC_FLUSH_COMMANDS_BIT: GL.Enum
    abstract SYNC_GPU_COMMANDS_COMPLETE: GL.Enum
    abstract SYNC_STATUS: GL.Enum
    abstract TEXTURE_2D_ARRAY: GL.Enum
    abstract TEXTURE_3D: GL.Enum
    abstract TEXTURE_BASE_LEVEL: GL.Enum
    abstract TEXTURE_BINDING_2D_ARRAY: GL.Enum
    abstract TEXTURE_BINDING_3D: GL.Enum
    abstract TEXTURE_COMPARE_FUNC: GL.Enum
    abstract TEXTURE_COMPARE_MODE: GL.Enum
    abstract TEXTURE_IMMUTABLE_FORMAT: GL.Enum
    abstract TEXTURE_IMMUTABLE_LEVELS: GL.Enum
    abstract TEXTURE_MAX_LEVEL: GL.Enum
    abstract TEXTURE_MAX_LOD: GL.Enum
    abstract TEXTURE_MIN_LOD: GL.Enum
    abstract TEXTURE_WRAP_R: GL.Enum
    abstract TIMEOUT_EXPIRED: GL.Enum
    abstract TIMEOUT_IGNORED: GL.Int64
    abstract TRANSFORM_FEEDBACK: GL.Enum
    abstract TRANSFORM_FEEDBACK_ACTIVE: GL.Enum
    abstract TRANSFORM_FEEDBACK_BINDING: GL.Enum
    abstract TRANSFORM_FEEDBACK_BUFFER: GL.Enum
    abstract TRANSFORM_FEEDBACK_BUFFER_BINDING: GL.Enum
    abstract TRANSFORM_FEEDBACK_BUFFER_MODE: GL.Enum
    abstract TRANSFORM_FEEDBACK_BUFFER_SIZE: GL.Enum
    abstract TRANSFORM_FEEDBACK_BUFFER_START: GL.Enum
    abstract TRANSFORM_FEEDBACK_PAUSED: GL.Enum
    abstract TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: GL.Enum
    abstract TRANSFORM_FEEDBACK_VARYINGS: GL.Enum
    abstract UNIFORM_ARRAY_STRIDE: GL.Enum
    abstract UNIFORM_BLOCK_ACTIVE_UNIFORMS: GL.Enum
    abstract UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES: GL.Enum
    abstract UNIFORM_BLOCK_BINDING: GL.Enum
    abstract UNIFORM_BLOCK_DATA_SIZE: GL.Enum
    abstract UNIFORM_BLOCK_INDEX: GL.Enum
    abstract UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER: GL.Enum
    abstract UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER: GL.Enum
    abstract UNIFORM_BUFFER: GL.Enum
    abstract UNIFORM_BUFFER_BINDING: GL.Enum
    abstract UNIFORM_BUFFER_OFFSET_ALIGNMENT: GL.Enum
    abstract UNIFORM_BUFFER_SIZE: GL.Enum
    abstract UNIFORM_BUFFER_START: GL.Enum
    abstract UNIFORM_IS_ROW_MAJOR: GL.Enum
    abstract UNIFORM_MATRIX_STRIDE: GL.Enum
    abstract UNIFORM_OFFSET: GL.Enum
    abstract UNIFORM_SIZE: GL.Enum
    abstract UNIFORM_TYPE: GL.Enum
    abstract UNPACK_IMAGE_HEIGHT: GL.Enum
    abstract UNPACK_ROW_LENGTH: GL.Enum
    abstract UNPACK_SKIP_IMAGES: GL.Enum
    abstract UNPACK_SKIP_PIXELS: GL.Enum
    abstract UNPACK_SKIP_ROWS: GL.Enum
    abstract UNSIGNALED: GL.Enum
    abstract UNSIGNED_INT_10F_11F_11F_REV: GL.Enum
    abstract UNSIGNED_INT_24_8: GL.Enum
    abstract UNSIGNED_INT_2_10_10_10_REV: GL.Enum
    abstract UNSIGNED_INT_5_9_9_9_REV: GL.Enum
    abstract UNSIGNED_INT_SAMPLER_2D: GL.Enum
    abstract UNSIGNED_INT_SAMPLER_2D_ARRAY: GL.Enum
    abstract UNSIGNED_INT_SAMPLER_3D: GL.Enum
    abstract UNSIGNED_INT_SAMPLER_CUBE: GL.Enum
    abstract UNSIGNED_INT_VEC2: GL.Enum
    abstract UNSIGNED_INT_VEC3: GL.Enum
    abstract UNSIGNED_INT_VEC4: GL.Enum
    abstract UNSIGNED_NORMALIZED: GL.Enum
    abstract VERTEX_ARRAY_BINDING: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_DIVISOR: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_INTEGER: GL.Enum
    abstract WAIT_FAILED: GL.Enum
    abstract ACTIVE_ATTRIBUTES: GL.Enum
    abstract ACTIVE_TEXTURE: GL.Enum
    abstract ACTIVE_UNIFORMS: GL.Enum
    abstract ALIASED_LINE_WIDTH_RANGE: GL.Enum
    abstract ALIASED_POINT_SIZE_RANGE: GL.Enum
    abstract ALPHA: GL.Enum
    abstract ALPHA_BITS: GL.Enum
    abstract ALWAYS: GL.Enum
    abstract ARRAY_BUFFER: GL.Enum
    abstract ARRAY_BUFFER_BINDING: GL.Enum
    abstract ATTACHED_SHADERS: GL.Enum
    abstract BACK: GL.Enum
    abstract BLEND: GL.Enum
    abstract BLEND_COLOR: GL.Enum
    abstract BLEND_DST_ALPHA: GL.Enum
    abstract BLEND_DST_RGB: GL.Enum
    abstract BLEND_EQUATION: GL.Enum
    abstract BLEND_EQUATION_ALPHA: GL.Enum
    abstract BLEND_EQUATION_RGB: GL.Enum
    abstract BLEND_SRC_ALPHA: GL.Enum
    abstract BLEND_SRC_RGB: GL.Enum
    abstract BLUE_BITS: GL.Enum
    abstract BOOL: GL.Enum
    abstract BOOL_VEC2: GL.Enum
    abstract BOOL_VEC3: GL.Enum
    abstract BOOL_VEC4: GL.Enum
    abstract BROWSER_DEFAULT_WEBGL: GL.Enum
    abstract BUFFER_SIZE: GL.Enum
    abstract BUFFER_USAGE: GL.Enum
    abstract BYTE: GL.Enum
    abstract CCW: GL.Enum
    abstract CLAMP_TO_EDGE: GL.Enum
    abstract COLOR_ATTACHMENT0: GL.Enum
    abstract COLOR_BUFFER_BIT: GL.Enum
    abstract COLOR_CLEAR_VALUE: GL.Enum
    abstract COLOR_WRITEMASK: GL.Enum
    abstract COMPILE_STATUS: GL.Enum
    abstract COMPRESSED_TEXTURE_FORMATS: GL.Enum
    abstract CONSTANT_ALPHA: GL.Enum
    abstract CONSTANT_COLOR: GL.Enum
    abstract CONTEXT_LOST_WEBGL: GL.Enum
    abstract CULL_FACE: GL.Enum
    abstract CULL_FACE_MODE: GL.Enum
    abstract CURRENT_PROGRAM: GL.Enum
    abstract CURRENT_VERTEX_ATTRIB: GL.Enum
    abstract CW: GL.Enum
    abstract DECR: GL.Enum
    abstract DECR_WRAP: GL.Enum
    abstract DELETE_STATUS: GL.Enum
    abstract DEPTH_ATTACHMENT: GL.Enum
    abstract DEPTH_BITS: GL.Enum
    abstract DEPTH_BUFFER_BIT: GL.Enum
    abstract DEPTH_CLEAR_VALUE: GL.Enum
    abstract DEPTH_COMPONENT: GL.Enum
    abstract DEPTH_COMPONENT16: GL.Enum
    abstract DEPTH_FUNC: GL.Enum
    abstract DEPTH_RANGE: GL.Enum
    abstract DEPTH_STENCIL: GL.Enum
    abstract DEPTH_STENCIL_ATTACHMENT: GL.Enum
    abstract DEPTH_TEST: GL.Enum
    abstract DEPTH_WRITEMASK: GL.Enum
    abstract DITHER: GL.Enum
    abstract DONT_CARE: GL.Enum
    abstract DST_ALPHA: GL.Enum
    abstract DST_COLOR: GL.Enum
    abstract DYNAMIC_DRAW: GL.Enum
    abstract ELEMENT_ARRAY_BUFFER: GL.Enum
    abstract ELEMENT_ARRAY_BUFFER_BINDING: GL.Enum
    abstract EQUAL: GL.Enum
    abstract FASTEST: GL.Enum
    abstract FLOAT: GL.Enum
    abstract FLOAT_MAT2: GL.Enum
    abstract FLOAT_MAT3: GL.Enum
    abstract FLOAT_MAT4: GL.Enum
    abstract FLOAT_VEC2: GL.Enum
    abstract FLOAT_VEC3: GL.Enum
    abstract FLOAT_VEC4: GL.Enum
    abstract FRAGMENT_SHADER: GL.Enum
    abstract FRAMEBUFFER: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: GL.Enum
    abstract FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: GL.Enum
    abstract FRAMEBUFFER_BINDING: GL.Enum
    abstract FRAMEBUFFER_COMPLETE: GL.Enum
    abstract FRAMEBUFFER_INCOMPLETE_ATTACHMENT: GL.Enum
    abstract FRAMEBUFFER_INCOMPLETE_DIMENSIONS: GL.Enum
    abstract FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: GL.Enum
    abstract FRAMEBUFFER_UNSUPPORTED: GL.Enum
    abstract FRONT: GL.Enum
    abstract FRONT_AND_BACK: GL.Enum
    abstract FRONT_FACE: GL.Enum
    abstract FUNC_ADD: GL.Enum
    abstract FUNC_REVERSE_SUBTRACT: GL.Enum
    abstract FUNC_SUBTRACT: GL.Enum
    abstract GENERATE_MIPMAP_HINT: GL.Enum
    abstract GEQUAL: GL.Enum
    abstract GREATER: GL.Enum
    abstract GREEN_BITS: GL.Enum
    abstract HIGH_FLOAT: GL.Enum
    abstract HIGH_INT: GL.Enum
    abstract IMPLEMENTATION_COLOR_READ_FORMAT: GL.Enum
    abstract IMPLEMENTATION_COLOR_READ_TYPE: GL.Enum
    abstract INCR: GL.Enum
    abstract INCR_WRAP: GL.Enum
    abstract INT: GL.Enum
    abstract INT_VEC2: GL.Enum
    abstract INT_VEC3: GL.Enum
    abstract INT_VEC4: GL.Enum
    abstract INVALID_ENUM: GL.Enum
    abstract INVALID_FRAMEBUFFER_OPERATION: GL.Enum
    abstract INVALID_OPERATION: GL.Enum
    abstract INVALID_VALUE: GL.Enum
    abstract INVERT: GL.Enum
    abstract KEEP: GL.Enum
    abstract LEQUAL: GL.Enum
    abstract LESS: GL.Enum
    abstract LINEAR: GL.Enum
    abstract LINEAR_MIPMAP_LINEAR: GL.Enum
    abstract LINEAR_MIPMAP_NEAREST: GL.Enum
    abstract LINES: GL.Enum
    abstract LINE_LOOP: GL.Enum
    abstract LINE_STRIP: GL.Enum
    abstract LINE_WIDTH: GL.Enum
    abstract LINK_STATUS: GL.Enum
    abstract LOW_FLOAT: GL.Enum
    abstract LOW_INT: GL.Enum
    abstract LUMINANCE: GL.Enum
    abstract LUMINANCE_ALPHA: GL.Enum
    abstract MAX_COMBINED_TEXTURE_IMAGE_UNITS: GL.Enum
    abstract MAX_CUBE_MAP_TEXTURE_SIZE: GL.Enum
    abstract MAX_FRAGMENT_UNIFORM_VECTORS: GL.Enum
    abstract MAX_RENDERBUFFER_SIZE: GL.Enum
    abstract MAX_TEXTURE_IMAGE_UNITS: GL.Enum
    abstract MAX_TEXTURE_SIZE: GL.Enum
    abstract MAX_VARYING_VECTORS: GL.Enum
    abstract MAX_VERTEX_ATTRIBS: GL.Enum
    abstract MAX_VERTEX_TEXTURE_IMAGE_UNITS: GL.Enum
    abstract MAX_VERTEX_UNIFORM_VECTORS: GL.Enum
    abstract MAX_VIEWPORT_DIMS: GL.Enum
    abstract MEDIUM_FLOAT: GL.Enum
    abstract MEDIUM_INT: GL.Enum
    abstract MIRRORED_REPEAT: GL.Enum
    abstract NEAREST: GL.Enum
    abstract NEAREST_MIPMAP_LINEAR: GL.Enum
    abstract NEAREST_MIPMAP_NEAREST: GL.Enum
    abstract NEVER: GL.Enum
    abstract NICEST: GL.Enum
    abstract NONE: GL.Enum
    abstract NOTEQUAL: GL.Enum
    abstract NO_ERROR: GL.Enum
    abstract ONE: GL.Enum
    abstract ONE_MINUS_CONSTANT_ALPHA: GL.Enum
    abstract ONE_MINUS_CONSTANT_COLOR: GL.Enum
    abstract ONE_MINUS_DST_ALPHA: GL.Enum
    abstract ONE_MINUS_DST_COLOR: GL.Enum
    abstract ONE_MINUS_SRC_ALPHA: GL.Enum
    abstract ONE_MINUS_SRC_COLOR: GL.Enum
    abstract OUT_OF_MEMORY: GL.Enum
    abstract PACK_ALIGNMENT: GL.Enum
    abstract POINTS: GL.Enum
    abstract POLYGON_OFFSET_FACTOR: GL.Enum
    abstract POLYGON_OFFSET_FILL: GL.Enum
    abstract POLYGON_OFFSET_UNITS: GL.Enum
    abstract RED_BITS: GL.Enum
    abstract RENDERBUFFER: GL.Enum
    abstract RENDERBUFFER_ALPHA_SIZE: GL.Enum
    abstract RENDERBUFFER_BINDING: GL.Enum
    abstract RENDERBUFFER_BLUE_SIZE: GL.Enum
    abstract RENDERBUFFER_DEPTH_SIZE: GL.Enum
    abstract RENDERBUFFER_GREEN_SIZE: GL.Enum
    abstract RENDERBUFFER_HEIGHT: GL.Enum
    abstract RENDERBUFFER_INTERNAL_FORMAT: GL.Enum
    abstract RENDERBUFFER_RED_SIZE: GL.Enum
    abstract RENDERBUFFER_STENCIL_SIZE: GL.Enum
    abstract RENDERBUFFER_WIDTH: GL.Enum
    abstract RENDERER: GL.Enum
    abstract REPEAT: GL.Enum
    abstract REPLACE: GL.Enum
    abstract RGB: GL.Enum
    abstract RGB565: GL.Enum
    abstract RGB5_A1: GL.Enum
    abstract RGBA: GL.Enum
    abstract RGBA4: GL.Enum
    abstract SAMPLER_2D: GL.Enum
    abstract SAMPLER_CUBE: GL.Enum
    abstract SAMPLES: GL.Enum
    abstract SAMPLE_ALPHA_TO_COVERAGE: GL.Enum
    abstract SAMPLE_BUFFERS: GL.Enum
    abstract SAMPLE_COVERAGE: GL.Enum
    abstract SAMPLE_COVERAGE_INVERT: GL.Enum
    abstract SAMPLE_COVERAGE_VALUE: GL.Enum
    abstract SCISSOR_BOX: GL.Enum
    abstract SCISSOR_TEST: GL.Enum
    abstract SHADER_TYPE: GL.Enum
    abstract SHADING_LANGUAGE_VERSION: GL.Enum
    abstract SHORT: GL.Enum
    abstract SRC_ALPHA: GL.Enum
    abstract SRC_ALPHA_SATURATE: GL.Enum
    abstract SRC_COLOR: GL.Enum
    abstract STATIC_DRAW: GL.Enum
    abstract STENCIL_ATTACHMENT: GL.Enum
    abstract STENCIL_BACK_FAIL: GL.Enum
    abstract STENCIL_BACK_FUNC: GL.Enum
    abstract STENCIL_BACK_PASS_DEPTH_FAIL: GL.Enum
    abstract STENCIL_BACK_PASS_DEPTH_PASS: GL.Enum
    abstract STENCIL_BACK_REF: GL.Enum
    abstract STENCIL_BACK_VALUE_MASK: GL.Enum
    abstract STENCIL_BACK_WRITEMASK: GL.Enum
    abstract STENCIL_BITS: GL.Enum
    abstract STENCIL_BUFFER_BIT: GL.Enum
    abstract STENCIL_CLEAR_VALUE: GL.Enum
    abstract STENCIL_FAIL: GL.Enum
    abstract STENCIL_FUNC: GL.Enum
    abstract STENCIL_INDEX8: GL.Enum
    abstract STENCIL_PASS_DEPTH_FAIL: GL.Enum
    abstract STENCIL_PASS_DEPTH_PASS: GL.Enum
    abstract STENCIL_REF: GL.Enum
    abstract STENCIL_TEST: GL.Enum
    abstract STENCIL_VALUE_MASK: GL.Enum
    abstract STENCIL_WRITEMASK: GL.Enum
    abstract STREAM_DRAW: GL.Enum
    abstract SUBPIXEL_BITS: GL.Enum
    abstract TEXTURE: GL.Enum
    abstract TEXTURE0: GL.Enum
    abstract TEXTURE1: GL.Enum
    abstract TEXTURE10: GL.Enum
    abstract TEXTURE11: GL.Enum
    abstract TEXTURE12: GL.Enum
    abstract TEXTURE13: GL.Enum
    abstract TEXTURE14: GL.Enum
    abstract TEXTURE15: GL.Enum
    abstract TEXTURE16: GL.Enum
    abstract TEXTURE17: GL.Enum
    abstract TEXTURE18: GL.Enum
    abstract TEXTURE19: GL.Enum
    abstract TEXTURE2: GL.Enum
    abstract TEXTURE20: GL.Enum
    abstract TEXTURE21: GL.Enum
    abstract TEXTURE22: GL.Enum
    abstract TEXTURE23: GL.Enum
    abstract TEXTURE24: GL.Enum
    abstract TEXTURE25: GL.Enum
    abstract TEXTURE26: GL.Enum
    abstract TEXTURE27: GL.Enum
    abstract TEXTURE28: GL.Enum
    abstract TEXTURE29: GL.Enum
    abstract TEXTURE3: GL.Enum
    abstract TEXTURE30: GL.Enum
    abstract TEXTURE31: GL.Enum
    abstract TEXTURE4: GL.Enum
    abstract TEXTURE5: GL.Enum
    abstract TEXTURE6: GL.Enum
    abstract TEXTURE7: GL.Enum
    abstract TEXTURE8: GL.Enum
    abstract TEXTURE9: GL.Enum
    abstract TEXTURE_2D: GL.Enum
    abstract TEXTURE_BINDING_2D: GL.Enum
    abstract TEXTURE_BINDING_CUBE_MAP: GL.Enum
    abstract TEXTURE_CUBE_MAP: GL.Enum
    abstract TEXTURE_CUBE_MAP_NEGATIVE_X: GL.Enum
    abstract TEXTURE_CUBE_MAP_NEGATIVE_Y: GL.Enum
    abstract TEXTURE_CUBE_MAP_NEGATIVE_Z: GL.Enum
    abstract TEXTURE_CUBE_MAP_POSITIVE_X: GL.Enum
    abstract TEXTURE_CUBE_MAP_POSITIVE_Y: GL.Enum
    abstract TEXTURE_CUBE_MAP_POSITIVE_Z: GL.Enum
    abstract TEXTURE_MAG_FILTER: GL.Enum
    abstract TEXTURE_MIN_FILTER: GL.Enum
    abstract TEXTURE_WRAP_S: GL.Enum
    abstract TEXTURE_WRAP_T: GL.Enum
    abstract TRIANGLES: GL.Enum
    abstract TRIANGLE_FAN: GL.Enum
    abstract TRIANGLE_STRIP: GL.Enum
    abstract UNPACK_ALIGNMENT: GL.Enum
    abstract UNPACK_COLORSPACE_CONVERSION_WEBGL: GL.Enum
    abstract UNPACK_FLIP_Y_WEBGL: GL.Enum
    abstract UNPACK_PREMULTIPLY_ALPHA_WEBGL: GL.Enum
    abstract UNSIGNED_BYTE: GL.Enum
    abstract UNSIGNED_INT: GL.Enum
    abstract UNSIGNED_SHORT: GL.Enum
    abstract UNSIGNED_SHORT_4_4_4_4: GL.Enum
    abstract UNSIGNED_SHORT_5_5_5_1: GL.Enum
    abstract UNSIGNED_SHORT_5_6_5: GL.Enum
    abstract VALIDATE_STATUS: GL.Enum
    abstract VENDOR: GL.Enum
    abstract VERSION: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_ENABLED: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_NORMALIZED: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_POINTER: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_SIZE: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_STRIDE: GL.Enum
    abstract VERTEX_ATTRIB_ARRAY_TYPE: GL.Enum
    abstract VERTEX_SHADER: GL.Enum
    abstract VIEWPORT: GL.Enum
    abstract ZERO: GL.Enum

open HTML.Types

[<AutoOpen>]
module RenderingContextExtension =
    type HTMLCanvasElement with
        [<Emit "$0.getContext('webgl2',$1)">]
        member __.getContext_webgl2(): RenderingContext = jsNative

    let [<Global>] WebGL2RenderingContext: RenderingContextType = jsNative
