// ts2fable 0.7.1
namespace WebGL2.RenderingContext

open System
open Fable.Core
open Fable.Core.JS

open WebGL.Types
open WebGL.Base
open WebGL2.Base
open WebGL2.Overloads

// let [<Import("WebGL2RenderingContextType","webgl2")>] WebGL2RenderingContextType: WebGL2RenderingContextType = jsNative

/// The WebGL2RenderingContext interface provides the OpenGL ES 3.0 rendering context for the drawing surface of an HTML <canvas> element.
/// To get an object of this interface, call `getContext()` on a `<canvas>` element, supplying `"webgl2"` as the argument:
/// ```
/// const canvas = document.getElementById('myCanvas');
/// const gl = canvas.getContext('webgl2');
/// ```
type [<AllowNullLiteral>] WebGL2RenderingContext =
    inherit WebGL2RenderingContextBase
    inherit WebGL2RenderingContextOverloads
    inherit WebGLRenderingContextBase

type [<AllowNullLiteral>] WebGL2RenderingContextType =
    abstract prototype: WebGL2RenderingContext with get, set
    [<Emit "new $0($1...)">] abstract Create: unit -> obj
    abstract ACTIVE_UNIFORM_BLOCKS: GLenum
    abstract ALREADY_SIGNALED: GLenum
    abstract ANY_SAMPLES_PASSED: GLenum
    abstract ANY_SAMPLES_PASSED_CONSERVATIVE: GLenum
    abstract COLOR: GLenum
    abstract COLOR_ATTACHMENT1: GLenum
    abstract COLOR_ATTACHMENT10: GLenum
    abstract COLOR_ATTACHMENT11: GLenum
    abstract COLOR_ATTACHMENT12: GLenum
    abstract COLOR_ATTACHMENT13: GLenum
    abstract COLOR_ATTACHMENT14: GLenum
    abstract COLOR_ATTACHMENT15: GLenum
    abstract COLOR_ATTACHMENT2: GLenum
    abstract COLOR_ATTACHMENT3: GLenum
    abstract COLOR_ATTACHMENT4: GLenum
    abstract COLOR_ATTACHMENT5: GLenum
    abstract COLOR_ATTACHMENT6: GLenum
    abstract COLOR_ATTACHMENT7: GLenum
    abstract COLOR_ATTACHMENT8: GLenum
    abstract COLOR_ATTACHMENT9: GLenum
    abstract COMPARE_REF_TO_TEXTURE: GLenum
    abstract CONDITION_SATISFIED: GLenum
    abstract COPY_READ_BUFFER: GLenum
    abstract COPY_READ_BUFFER_BINDING: GLenum
    abstract COPY_WRITE_BUFFER: GLenum
    abstract COPY_WRITE_BUFFER_BINDING: GLenum
    abstract CURRENT_QUERY: GLenum
    abstract DEPTH: GLenum
    abstract DEPTH24_STENCIL8: GLenum
    abstract DEPTH32F_STENCIL8: GLenum
    abstract DEPTH_COMPONENT24: GLenum
    abstract DEPTH_COMPONENT32F: GLenum
    abstract DRAW_BUFFER0: GLenum
    abstract DRAW_BUFFER1: GLenum
    abstract DRAW_BUFFER10: GLenum
    abstract DRAW_BUFFER11: GLenum
    abstract DRAW_BUFFER12: GLenum
    abstract DRAW_BUFFER13: GLenum
    abstract DRAW_BUFFER14: GLenum
    abstract DRAW_BUFFER15: GLenum
    abstract DRAW_BUFFER2: GLenum
    abstract DRAW_BUFFER3: GLenum
    abstract DRAW_BUFFER4: GLenum
    abstract DRAW_BUFFER5: GLenum
    abstract DRAW_BUFFER6: GLenum
    abstract DRAW_BUFFER7: GLenum
    abstract DRAW_BUFFER8: GLenum
    abstract DRAW_BUFFER9: GLenum
    abstract DRAW_FRAMEBUFFER: GLenum
    abstract DRAW_FRAMEBUFFER_BINDING: GLenum
    abstract DYNAMIC_COPY: GLenum
    abstract DYNAMIC_READ: GLenum
    abstract FLOAT_32_UNSIGNED_INT_24_8_REV: GLenum
    abstract FLOAT_MAT2x3: GLenum
    abstract FLOAT_MAT2x4: GLenum
    abstract FLOAT_MAT3x2: GLenum
    abstract FLOAT_MAT3x4: GLenum
    abstract FLOAT_MAT4x2: GLenum
    abstract FLOAT_MAT4x3: GLenum
    abstract FRAGMENT_SHADER_DERIVATIVE_HINT: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_BLUE_SIZE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_RED_SIZE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER: GLenum
    abstract FRAMEBUFFER_DEFAULT: GLenum
    abstract FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: GLenum
    abstract HALF_FLOAT: GLenum
    abstract INTERLEAVED_ATTRIBS: GLenum
    abstract INT_2_10_10_10_REV: GLenum
    abstract INT_SAMPLER_2D: GLenum
    abstract INT_SAMPLER_2D_ARRAY: GLenum
    abstract INT_SAMPLER_3D: GLenum
    abstract INT_SAMPLER_CUBE: GLenum
    abstract INVALID_INDEX: GLenum
    abstract MAX: GLenum
    abstract MAX_3D_TEXTURE_SIZE: GLenum
    abstract MAX_ARRAY_TEXTURE_LAYERS: GLenum
    abstract MAX_CLIENT_WAIT_TIMEOUT_WEBGL: GLenum
    abstract MAX_COLOR_ATTACHMENTS: GLenum
    abstract MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: GLenum
    abstract MAX_COMBINED_UNIFORM_BLOCKS: GLenum
    abstract MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS: GLenum
    abstract MAX_DRAW_BUFFERS: GLenum
    abstract MAX_ELEMENTS_INDICES: GLenum
    abstract MAX_ELEMENTS_VERTICES: GLenum
    abstract MAX_ELEMENT_INDEX: GLenum
    abstract MAX_FRAGMENT_INPUT_COMPONENTS: GLenum
    abstract MAX_FRAGMENT_UNIFORM_BLOCKS: GLenum
    abstract MAX_FRAGMENT_UNIFORM_COMPONENTS: GLenum
    abstract MAX_PROGRAM_TEXEL_OFFSET: GLenum
    abstract MAX_SAMPLES: GLenum
    abstract MAX_SERVER_WAIT_TIMEOUT: GLenum
    abstract MAX_TEXTURE_LOD_BIAS: GLenum
    abstract MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: GLenum
    abstract MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS: GLenum
    abstract MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS: GLenum
    abstract MAX_UNIFORM_BLOCK_SIZE: GLenum
    abstract MAX_UNIFORM_BUFFER_BINDINGS: GLenum
    abstract MAX_VARYING_COMPONENTS: GLenum
    abstract MAX_VERTEX_OUTPUT_COMPONENTS: GLenum
    abstract MAX_VERTEX_UNIFORM_BLOCKS: GLenum
    abstract MAX_VERTEX_UNIFORM_COMPONENTS: GLenum
    abstract MIN: GLenum
    abstract MIN_PROGRAM_TEXEL_OFFSET: GLenum
    abstract OBJECT_TYPE: GLenum
    abstract PACK_ROW_LENGTH: GLenum
    abstract PACK_SKIP_PIXELS: GLenum
    abstract PACK_SKIP_ROWS: GLenum
    abstract PIXEL_PACK_BUFFER: GLenum
    abstract PIXEL_PACK_BUFFER_BINDING: GLenum
    abstract PIXEL_UNPACK_BUFFER: GLenum
    abstract PIXEL_UNPACK_BUFFER_BINDING: GLenum
    abstract QUERY_RESULT: GLenum
    abstract QUERY_RESULT_AVAILABLE: GLenum
    abstract R11F_G11F_B10F: GLenum
    abstract R16F: GLenum
    abstract R16I: GLenum
    abstract R16UI: GLenum
    abstract R32F: GLenum
    abstract R32I: GLenum
    abstract R32UI: GLenum
    abstract R8: GLenum
    abstract R8I: GLenum
    abstract R8UI: GLenum
    abstract R8_SNORM: GLenum
    abstract RASTERIZER_DISCARD: GLenum
    abstract READ_BUFFER: GLenum
    abstract READ_FRAMEBUFFER: GLenum
    abstract READ_FRAMEBUFFER_BINDING: GLenum
    abstract RED: GLenum
    abstract RED_INTEGER: GLenum
    abstract RENDERBUFFER_SAMPLES: GLenum
    abstract RG: GLenum
    abstract RG16F: GLenum
    abstract RG16I: GLenum
    abstract RG16UI: GLenum
    abstract RG32F: GLenum
    abstract RG32I: GLenum
    abstract RG32UI: GLenum
    abstract RG8: GLenum
    abstract RG8I: GLenum
    abstract RG8UI: GLenum
    abstract RG8_SNORM: GLenum
    abstract RGB10_A2: GLenum
    abstract RGB10_A2UI: GLenum
    abstract RGB16F: GLenum
    abstract RGB16I: GLenum
    abstract RGB16UI: GLenum
    abstract RGB32F: GLenum
    abstract RGB32I: GLenum
    abstract RGB32UI: GLenum
    abstract RGB8: GLenum
    abstract RGB8I: GLenum
    abstract RGB8UI: GLenum
    abstract RGB8_SNORM: GLenum
    abstract RGB9_E5: GLenum
    abstract RGBA16F: GLenum
    abstract RGBA16I: GLenum
    abstract RGBA16UI: GLenum
    abstract RGBA32F: GLenum
    abstract RGBA32I: GLenum
    abstract RGBA32UI: GLenum
    abstract RGBA8: GLenum
    abstract RGBA8I: GLenum
    abstract RGBA8UI: GLenum
    abstract RGBA8_SNORM: GLenum
    abstract RGBA_INTEGER: GLenum
    abstract RGB_INTEGER: GLenum
    abstract RG_INTEGER: GLenum
    abstract SAMPLER_2D_ARRAY: GLenum
    abstract SAMPLER_2D_ARRAY_SHADOW: GLenum
    abstract SAMPLER_2D_SHADOW: GLenum
    abstract SAMPLER_3D: GLenum
    abstract SAMPLER_BINDING: GLenum
    abstract SAMPLER_CUBE_SHADOW: GLenum
    abstract SEPARATE_ATTRIBS: GLenum
    abstract SIGNALED: GLenum
    abstract SIGNED_NORMALIZED: GLenum
    abstract SRGB: GLenum
    abstract SRGB8: GLenum
    abstract SRGB8_ALPHA8: GLenum
    abstract STATIC_COPY: GLenum
    abstract STATIC_READ: GLenum
    abstract STENCIL: GLenum
    abstract STREAM_COPY: GLenum
    abstract STREAM_READ: GLenum
    abstract SYNC_CONDITION: GLenum
    abstract SYNC_FENCE: GLenum
    abstract SYNC_FLAGS: GLenum
    abstract SYNC_FLUSH_COMMANDS_BIT: GLenum
    abstract SYNC_GPU_COMMANDS_COMPLETE: GLenum
    abstract SYNC_STATUS: GLenum
    abstract TEXTURE_2D_ARRAY: GLenum
    abstract TEXTURE_3D: GLenum
    abstract TEXTURE_BASE_LEVEL: GLenum
    abstract TEXTURE_BINDING_2D_ARRAY: GLenum
    abstract TEXTURE_BINDING_3D: GLenum
    abstract TEXTURE_COMPARE_FUNC: GLenum
    abstract TEXTURE_COMPARE_MODE: GLenum
    abstract TEXTURE_IMMUTABLE_FORMAT: GLenum
    abstract TEXTURE_IMMUTABLE_LEVELS: GLenum
    abstract TEXTURE_MAX_LEVEL: GLenum
    abstract TEXTURE_MAX_LOD: GLenum
    abstract TEXTURE_MIN_LOD: GLenum
    abstract TEXTURE_WRAP_R: GLenum
    abstract TIMEOUT_EXPIRED: GLenum
    abstract TIMEOUT_IGNORED: GLint64
    abstract TRANSFORM_FEEDBACK: GLenum
    abstract TRANSFORM_FEEDBACK_ACTIVE: GLenum
    abstract TRANSFORM_FEEDBACK_BINDING: GLenum
    abstract TRANSFORM_FEEDBACK_BUFFER: GLenum
    abstract TRANSFORM_FEEDBACK_BUFFER_BINDING: GLenum
    abstract TRANSFORM_FEEDBACK_BUFFER_MODE: GLenum
    abstract TRANSFORM_FEEDBACK_BUFFER_SIZE: GLenum
    abstract TRANSFORM_FEEDBACK_BUFFER_START: GLenum
    abstract TRANSFORM_FEEDBACK_PAUSED: GLenum
    abstract TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: GLenum
    abstract TRANSFORM_FEEDBACK_VARYINGS: GLenum
    abstract UNIFORM_ARRAY_STRIDE: GLenum
    abstract UNIFORM_BLOCK_ACTIVE_UNIFORMS: GLenum
    abstract UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES: GLenum
    abstract UNIFORM_BLOCK_BINDING: GLenum
    abstract UNIFORM_BLOCK_DATA_SIZE: GLenum
    abstract UNIFORM_BLOCK_INDEX: GLenum
    abstract UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER: GLenum
    abstract UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER: GLenum
    abstract UNIFORM_BUFFER: GLenum
    abstract UNIFORM_BUFFER_BINDING: GLenum
    abstract UNIFORM_BUFFER_OFFSET_ALIGNMENT: GLenum
    abstract UNIFORM_BUFFER_SIZE: GLenum
    abstract UNIFORM_BUFFER_START: GLenum
    abstract UNIFORM_IS_ROW_MAJOR: GLenum
    abstract UNIFORM_MATRIX_STRIDE: GLenum
    abstract UNIFORM_OFFSET: GLenum
    abstract UNIFORM_SIZE: GLenum
    abstract UNIFORM_TYPE: GLenum
    abstract UNPACK_IMAGE_HEIGHT: GLenum
    abstract UNPACK_ROW_LENGTH: GLenum
    abstract UNPACK_SKIP_IMAGES: GLenum
    abstract UNPACK_SKIP_PIXELS: GLenum
    abstract UNPACK_SKIP_ROWS: GLenum
    abstract UNSIGNALED: GLenum
    abstract UNSIGNED_INT_10F_11F_11F_REV: GLenum
    abstract UNSIGNED_INT_24_8: GLenum
    abstract UNSIGNED_INT_2_10_10_10_REV: GLenum
    abstract UNSIGNED_INT_5_9_9_9_REV: GLenum
    abstract UNSIGNED_INT_SAMPLER_2D: GLenum
    abstract UNSIGNED_INT_SAMPLER_2D_ARRAY: GLenum
    abstract UNSIGNED_INT_SAMPLER_3D: GLenum
    abstract UNSIGNED_INT_SAMPLER_CUBE: GLenum
    abstract UNSIGNED_INT_VEC2: GLenum
    abstract UNSIGNED_INT_VEC3: GLenum
    abstract UNSIGNED_INT_VEC4: GLenum
    abstract UNSIGNED_NORMALIZED: GLenum
    abstract VERTEX_ARRAY_BINDING: GLenum
    abstract VERTEX_ATTRIB_ARRAY_DIVISOR: GLenum
    abstract VERTEX_ATTRIB_ARRAY_INTEGER: GLenum
    abstract WAIT_FAILED: GLenum
    abstract ACTIVE_ATTRIBUTES: GLenum
    abstract ACTIVE_TEXTURE: GLenum
    abstract ACTIVE_UNIFORMS: GLenum
    abstract ALIASED_LINE_WIDTH_RANGE: GLenum
    abstract ALIASED_POINT_SIZE_RANGE: GLenum
    abstract ALPHA: GLenum
    abstract ALPHA_BITS: GLenum
    abstract ALWAYS: GLenum
    abstract ARRAY_BUFFER: GLenum
    abstract ARRAY_BUFFER_BINDING: GLenum
    abstract ATTACHED_SHADERS: GLenum
    abstract BACK: GLenum
    abstract BLEND: GLenum
    abstract BLEND_COLOR: GLenum
    abstract BLEND_DST_ALPHA: GLenum
    abstract BLEND_DST_RGB: GLenum
    abstract BLEND_EQUATION: GLenum
    abstract BLEND_EQUATION_ALPHA: GLenum
    abstract BLEND_EQUATION_RGB: GLenum
    abstract BLEND_SRC_ALPHA: GLenum
    abstract BLEND_SRC_RGB: GLenum
    abstract BLUE_BITS: GLenum
    abstract BOOL: GLenum
    abstract BOOL_VEC2: GLenum
    abstract BOOL_VEC3: GLenum
    abstract BOOL_VEC4: GLenum
    abstract BROWSER_DEFAULT_WEBGL: GLenum
    abstract BUFFER_SIZE: GLenum
    abstract BUFFER_USAGE: GLenum
    abstract BYTE: GLenum
    abstract CCW: GLenum
    abstract CLAMP_TO_EDGE: GLenum
    abstract COLOR_ATTACHMENT0: GLenum
    abstract COLOR_BUFFER_BIT: GLenum
    abstract COLOR_CLEAR_VALUE: GLenum
    abstract COLOR_WRITEMASK: GLenum
    abstract COMPILE_STATUS: GLenum
    abstract COMPRESSED_TEXTURE_FORMATS: GLenum
    abstract CONSTANT_ALPHA: GLenum
    abstract CONSTANT_COLOR: GLenum
    abstract CONTEXT_LOST_WEBGL: GLenum
    abstract CULL_FACE: GLenum
    abstract CULL_FACE_MODE: GLenum
    abstract CURRENT_PROGRAM: GLenum
    abstract CURRENT_VERTEX_ATTRIB: GLenum
    abstract CW: GLenum
    abstract DECR: GLenum
    abstract DECR_WRAP: GLenum
    abstract DELETE_STATUS: GLenum
    abstract DEPTH_ATTACHMENT: GLenum
    abstract DEPTH_BITS: GLenum
    abstract DEPTH_BUFFER_BIT: GLenum
    abstract DEPTH_CLEAR_VALUE: GLenum
    abstract DEPTH_COMPONENT: GLenum
    abstract DEPTH_COMPONENT16: GLenum
    abstract DEPTH_FUNC: GLenum
    abstract DEPTH_RANGE: GLenum
    abstract DEPTH_STENCIL: GLenum
    abstract DEPTH_STENCIL_ATTACHMENT: GLenum
    abstract DEPTH_TEST: GLenum
    abstract DEPTH_WRITEMASK: GLenum
    abstract DITHER: GLenum
    abstract DONT_CARE: GLenum
    abstract DST_ALPHA: GLenum
    abstract DST_COLOR: GLenum
    abstract DYNAMIC_DRAW: GLenum
    abstract ELEMENT_ARRAY_BUFFER: GLenum
    abstract ELEMENT_ARRAY_BUFFER_BINDING: GLenum
    abstract EQUAL: GLenum
    abstract FASTEST: GLenum
    abstract FLOAT: GLenum
    abstract FLOAT_MAT2: GLenum
    abstract FLOAT_MAT3: GLenum
    abstract FLOAT_MAT4: GLenum
    abstract FLOAT_VEC2: GLenum
    abstract FLOAT_VEC3: GLenum
    abstract FLOAT_VEC4: GLenum
    abstract FRAGMENT_SHADER: GLenum
    abstract FRAMEBUFFER: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: GLenum
    abstract FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: GLenum
    abstract FRAMEBUFFER_BINDING: GLenum
    abstract FRAMEBUFFER_COMPLETE: GLenum
    abstract FRAMEBUFFER_INCOMPLETE_ATTACHMENT: GLenum
    abstract FRAMEBUFFER_INCOMPLETE_DIMENSIONS: GLenum
    abstract FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: GLenum
    abstract FRAMEBUFFER_UNSUPPORTED: GLenum
    abstract FRONT: GLenum
    abstract FRONT_AND_BACK: GLenum
    abstract FRONT_FACE: GLenum
    abstract FUNC_ADD: GLenum
    abstract FUNC_REVERSE_SUBTRACT: GLenum
    abstract FUNC_SUBTRACT: GLenum
    abstract GENERATE_MIPMAP_HINT: GLenum
    abstract GEQUAL: GLenum
    abstract GREATER: GLenum
    abstract GREEN_BITS: GLenum
    abstract HIGH_FLOAT: GLenum
    abstract HIGH_INT: GLenum
    abstract IMPLEMENTATION_COLOR_READ_FORMAT: GLenum
    abstract IMPLEMENTATION_COLOR_READ_TYPE: GLenum
    abstract INCR: GLenum
    abstract INCR_WRAP: GLenum
    abstract INT: GLenum
    abstract INT_VEC2: GLenum
    abstract INT_VEC3: GLenum
    abstract INT_VEC4: GLenum
    abstract INVALID_ENUM: GLenum
    abstract INVALID_FRAMEBUFFER_OPERATION: GLenum
    abstract INVALID_OPERATION: GLenum
    abstract INVALID_VALUE: GLenum
    abstract INVERT: GLenum
    abstract KEEP: GLenum
    abstract LEQUAL: GLenum
    abstract LESS: GLenum
    abstract LINEAR: GLenum
    abstract LINEAR_MIPMAP_LINEAR: GLenum
    abstract LINEAR_MIPMAP_NEAREST: GLenum
    abstract LINES: GLenum
    abstract LINE_LOOP: GLenum
    abstract LINE_STRIP: GLenum
    abstract LINE_WIDTH: GLenum
    abstract LINK_STATUS: GLenum
    abstract LOW_FLOAT: GLenum
    abstract LOW_INT: GLenum
    abstract LUMINANCE: GLenum
    abstract LUMINANCE_ALPHA: GLenum
    abstract MAX_COMBINED_TEXTURE_IMAGE_UNITS: GLenum
    abstract MAX_CUBE_MAP_TEXTURE_SIZE: GLenum
    abstract MAX_FRAGMENT_UNIFORM_VECTORS: GLenum
    abstract MAX_RENDERBUFFER_SIZE: GLenum
    abstract MAX_TEXTURE_IMAGE_UNITS: GLenum
    abstract MAX_TEXTURE_SIZE: GLenum
    abstract MAX_VARYING_VECTORS: GLenum
    abstract MAX_VERTEX_ATTRIBS: GLenum
    abstract MAX_VERTEX_TEXTURE_IMAGE_UNITS: GLenum
    abstract MAX_VERTEX_UNIFORM_VECTORS: GLenum
    abstract MAX_VIEWPORT_DIMS: GLenum
    abstract MEDIUM_FLOAT: GLenum
    abstract MEDIUM_INT: GLenum
    abstract MIRRORED_REPEAT: GLenum
    abstract NEAREST: GLenum
    abstract NEAREST_MIPMAP_LINEAR: GLenum
    abstract NEAREST_MIPMAP_NEAREST: GLenum
    abstract NEVER: GLenum
    abstract NICEST: GLenum
    abstract NONE: GLenum
    abstract NOTEQUAL: GLenum
    abstract NO_ERROR: GLenum
    abstract ONE: GLenum
    abstract ONE_MINUS_CONSTANT_ALPHA: GLenum
    abstract ONE_MINUS_CONSTANT_COLOR: GLenum
    abstract ONE_MINUS_DST_ALPHA: GLenum
    abstract ONE_MINUS_DST_COLOR: GLenum
    abstract ONE_MINUS_SRC_ALPHA: GLenum
    abstract ONE_MINUS_SRC_COLOR: GLenum
    abstract OUT_OF_MEMORY: GLenum
    abstract PACK_ALIGNMENT: GLenum
    abstract POINTS: GLenum
    abstract POLYGON_OFFSET_FACTOR: GLenum
    abstract POLYGON_OFFSET_FILL: GLenum
    abstract POLYGON_OFFSET_UNITS: GLenum
    abstract RED_BITS: GLenum
    abstract RENDERBUFFER: GLenum
    abstract RENDERBUFFER_ALPHA_SIZE: GLenum
    abstract RENDERBUFFER_BINDING: GLenum
    abstract RENDERBUFFER_BLUE_SIZE: GLenum
    abstract RENDERBUFFER_DEPTH_SIZE: GLenum
    abstract RENDERBUFFER_GREEN_SIZE: GLenum
    abstract RENDERBUFFER_HEIGHT: GLenum
    abstract RENDERBUFFER_INTERNAL_FORMAT: GLenum
    abstract RENDERBUFFER_RED_SIZE: GLenum
    abstract RENDERBUFFER_STENCIL_SIZE: GLenum
    abstract RENDERBUFFER_WIDTH: GLenum
    abstract RENDERER: GLenum
    abstract REPEAT: GLenum
    abstract REPLACE: GLenum
    abstract RGB: GLenum
    abstract RGB565: GLenum
    abstract RGB5_A1: GLenum
    abstract RGBA: GLenum
    abstract RGBA4: GLenum
    abstract SAMPLER_2D: GLenum
    abstract SAMPLER_CUBE: GLenum
    abstract SAMPLES: GLenum
    abstract SAMPLE_ALPHA_TO_COVERAGE: GLenum
    abstract SAMPLE_BUFFERS: GLenum
    abstract SAMPLE_COVERAGE: GLenum
    abstract SAMPLE_COVERAGE_INVERT: GLenum
    abstract SAMPLE_COVERAGE_VALUE: GLenum
    abstract SCISSOR_BOX: GLenum
    abstract SCISSOR_TEST: GLenum
    abstract SHADER_TYPE: GLenum
    abstract SHADING_LANGUAGE_VERSION: GLenum
    abstract SHORT: GLenum
    abstract SRC_ALPHA: GLenum
    abstract SRC_ALPHA_SATURATE: GLenum
    abstract SRC_COLOR: GLenum
    abstract STATIC_DRAW: GLenum
    abstract STENCIL_ATTACHMENT: GLenum
    abstract STENCIL_BACK_FAIL: GLenum
    abstract STENCIL_BACK_FUNC: GLenum
    abstract STENCIL_BACK_PASS_DEPTH_FAIL: GLenum
    abstract STENCIL_BACK_PASS_DEPTH_PASS: GLenum
    abstract STENCIL_BACK_REF: GLenum
    abstract STENCIL_BACK_VALUE_MASK: GLenum
    abstract STENCIL_BACK_WRITEMASK: GLenum
    abstract STENCIL_BITS: GLenum
    abstract STENCIL_BUFFER_BIT: GLenum
    abstract STENCIL_CLEAR_VALUE: GLenum
    abstract STENCIL_FAIL: GLenum
    abstract STENCIL_FUNC: GLenum
    abstract STENCIL_INDEX8: GLenum
    abstract STENCIL_PASS_DEPTH_FAIL: GLenum
    abstract STENCIL_PASS_DEPTH_PASS: GLenum
    abstract STENCIL_REF: GLenum
    abstract STENCIL_TEST: GLenum
    abstract STENCIL_VALUE_MASK: GLenum
    abstract STENCIL_WRITEMASK: GLenum
    abstract STREAM_DRAW: GLenum
    abstract SUBPIXEL_BITS: GLenum
    abstract TEXTURE: GLenum
    abstract TEXTURE0: GLenum
    abstract TEXTURE1: GLenum
    abstract TEXTURE10: GLenum
    abstract TEXTURE11: GLenum
    abstract TEXTURE12: GLenum
    abstract TEXTURE13: GLenum
    abstract TEXTURE14: GLenum
    abstract TEXTURE15: GLenum
    abstract TEXTURE16: GLenum
    abstract TEXTURE17: GLenum
    abstract TEXTURE18: GLenum
    abstract TEXTURE19: GLenum
    abstract TEXTURE2: GLenum
    abstract TEXTURE20: GLenum
    abstract TEXTURE21: GLenum
    abstract TEXTURE22: GLenum
    abstract TEXTURE23: GLenum
    abstract TEXTURE24: GLenum
    abstract TEXTURE25: GLenum
    abstract TEXTURE26: GLenum
    abstract TEXTURE27: GLenum
    abstract TEXTURE28: GLenum
    abstract TEXTURE29: GLenum
    abstract TEXTURE3: GLenum
    abstract TEXTURE30: GLenum
    abstract TEXTURE31: GLenum
    abstract TEXTURE4: GLenum
    abstract TEXTURE5: GLenum
    abstract TEXTURE6: GLenum
    abstract TEXTURE7: GLenum
    abstract TEXTURE8: GLenum
    abstract TEXTURE9: GLenum
    abstract TEXTURE_2D: GLenum
    abstract TEXTURE_BINDING_2D: GLenum
    abstract TEXTURE_BINDING_CUBE_MAP: GLenum
    abstract TEXTURE_CUBE_MAP: GLenum
    abstract TEXTURE_CUBE_MAP_NEGATIVE_X: GLenum
    abstract TEXTURE_CUBE_MAP_NEGATIVE_Y: GLenum
    abstract TEXTURE_CUBE_MAP_NEGATIVE_Z: GLenum
    abstract TEXTURE_CUBE_MAP_POSITIVE_X: GLenum
    abstract TEXTURE_CUBE_MAP_POSITIVE_Y: GLenum
    abstract TEXTURE_CUBE_MAP_POSITIVE_Z: GLenum
    abstract TEXTURE_MAG_FILTER: GLenum
    abstract TEXTURE_MIN_FILTER: GLenum
    abstract TEXTURE_WRAP_S: GLenum
    abstract TEXTURE_WRAP_T: GLenum
    abstract TRIANGLES: GLenum
    abstract TRIANGLE_FAN: GLenum
    abstract TRIANGLE_STRIP: GLenum
    abstract UNPACK_ALIGNMENT: GLenum
    abstract UNPACK_COLORSPACE_CONVERSION_WEBGL: GLenum
    abstract UNPACK_FLIP_Y_WEBGL: GLenum
    abstract UNPACK_PREMULTIPLY_ALPHA_WEBGL: GLenum
    abstract UNSIGNED_BYTE: GLenum
    abstract UNSIGNED_INT: GLenum
    abstract UNSIGNED_SHORT: GLenum
    abstract UNSIGNED_SHORT_4_4_4_4: GLenum
    abstract UNSIGNED_SHORT_5_5_5_1: GLenum
    abstract UNSIGNED_SHORT_5_6_5: GLenum
    abstract VALIDATE_STATUS: GLenum
    abstract VENDOR: GLenum
    abstract VERSION: GLenum
    abstract VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: GLenum
    abstract VERTEX_ATTRIB_ARRAY_ENABLED: GLenum
    abstract VERTEX_ATTRIB_ARRAY_NORMALIZED: GLenum
    abstract VERTEX_ATTRIB_ARRAY_POINTER: GLenum
    abstract VERTEX_ATTRIB_ARRAY_SIZE: GLenum
    abstract VERTEX_ATTRIB_ARRAY_STRIDE: GLenum
    abstract VERTEX_ATTRIB_ARRAY_TYPE: GLenum
    abstract VERTEX_SHADER: GLenum
    abstract VIEWPORT: GLenum
    abstract ZERO: GLenum

namespace WebGL2

open Fable.Core
open HTML.Types
open WebGL2.RenderingContext

[<AutoOpen>]
module WebGL2RenderingContext =
    type HTMLCanvasElement with
        [<Emit "$0.getContext('webgl2',$1)">]
        member __.getContext_webgl2(): WebGL2RenderingContext = jsNative

    let [<Global>] WebGL2RenderingContext: WebGL2RenderingContextType = jsNative